# whitelist long living branches
branches:
  only:
    - master

environment:
  matrix:
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - yarn --version
  - yarn install

build_script:
  - yarn build

test_script:
  - yarn test

  # Edge is not available on Windows Server
  # - yarn run lerna run test-edge
